# Data Preparation: Part 1 - Anomaly Code

## 1. Import Packages & Define Custom Functions

In [1]:
import pandas as pd
import re

In [2]:
# Using custom function from Michael Albert's class

def summarize_dataframe(df):
    missing_values = pd.concat([pd.DataFrame(df.columns, columns=['Variable Name']), 
                      pd.DataFrame(df.dtypes.values.reshape([-1,1]), columns=['Data Type']),
                      pd.DataFrame(df.isnull().sum().values, columns=['Missing Values']), 
                      pd.DataFrame([df[name].nunique() for name in df.columns], columns=['Unique Values'])], 
                     axis=1).set_index('Variable Name')
    return pd.concat([missing_values, df.describe(include='all').transpose()], axis=1).fillna("")

## 2. Import Raw Data

In [3]:
full = pd.read_csv('/home/jovyan/MSBA Mod 5/Final Deliverable/Data Cleaning and Feature Engineering/Raw Input Files/asrs_full.csv')

## 3. Clean Data

### 3.1. Preliminary Category Aggregation

In [4]:
aggregate_others = ['Other uav report', 'Other Fatigue', 'Other UAV', 'Other Service Road signs needed']

full.loc[full['anomaly_code'].isin(aggregate_others), 'anomaly_code'] = 'No Specific Anomaly Occurred All Types'

In [5]:
other_lasers = ['Other LASER']

full.loc[full['anomaly_code'].isin(other_lasers), 'anomaly_code'] = 'Inflight Event / Encounter Laser'

### 3.2. Identify Unique Categories

In [6]:
anomalies = full.anomaly_code

In [7]:
disaggregated_anomalies = []
for phrase in anomalies:
    disaggregated_anomalies.extend([s.strip() for s in re.split(r';', phrase)])

In [8]:
disaggregated_anomalies = pd.Series(disaggregated_anomalies)

In [9]:
# Counts
value_counts = disaggregated_anomalies.value_counts().reset_index()
value_counts.columns = ["Anomaly", "Count"]

In [10]:
with pd.option_context('display.max_rows', None):
    display(value_counts)

                                              Anomaly  Count
0   Deviation / Discrepancy - Procedural Published...  19131
1                 Aircraft Equipment Problem Critical   8227
2      Deviation / Discrepancy - Procedural Clearance   7843
3                                 ATC Issue All Types   6020
4              Aircraft Equipment Problem Less Severe   5605
5            Deviation / Discrepancy - Procedural FAR   3935
6                                       Conflict NMAC   3335
7              Inflight Event / Encounter CFTT / CFIT   3180
8     Inflight Event / Encounter Weather / Turbulence   2878
9               Deviation - Track / Heading All Types   2374
10                           Conflict Ground Conflict   2301
11  Ground Event / Encounter Loss Of Aircraft Control   2103
12  Flight Deck / Cabin / Aircraft Event Smoke / F...   1884
13  Deviation - Altitude Excursion From Assigned A...   1821
14                                           Critical   1804
15                         Conflict Airborne Conflict   1521
16   Deviation / Discrepancy - Procedural Maintenance   1501
17  Deviation / Discrepancy - Procedural Hazardous...   1302
18                       Airspace Violation All Types   1248
19   Inflight Event / Encounter Unstabilized Approach   1238
20  Inflight Event / Encounter Loss Of Aircraft Co...   1181
21                     Deviation - Altitude Overshoot   1144
22                        Deviation - Speed All Types   1114
23           Ground Event / Encounter Other / Unknown   1094
24                            Ground Excursion Runway   1006
25              Inflight Event / Encounter Fuel Issue    928
26   Inflight Event / Encounter Wake Vortex Encounter    912
27  Deviation / Discrepancy - Procedural Weight An...    850
28                            Ground Incursion Runway    842
29  Flight Deck / Cabin / Aircraft Event Illness /...    795
30  Flight Deck / Cabin / Aircraft Event Other / U...    643
31     Deviation / Discrepancy - Procedural MEL / CDL    638
32    Ground Event / Encounter Ground Equipment Issue    625
33  Ground Event / Encounter Ground Strike - Aircraft    606
34                           Ground Incursion Taxiway    566
35  Deviation - Altitude Crossing Restriction Not Met    555
36                                        Less Severe    497
37  Deviation / Discrepancy - Procedural Unauthori...    471
38                    Ground Event / Encounter Object    432
39      Ground Event / Encounter Weather / Turbulence    427
40         Inflight Event / Encounter Other / Unknown    386
41  Flight Deck / Cabin / Aircraft Event Passenger...    309
42    No Specific Anomaly Occurred Unwanted Situation    301
43                    Deviation - Altitude Undershoot    256
44                           Ground Excursion Taxiway    199
45  Deviation / Discrepancy - Procedural Other / U...    191
46                   Ground Event / Encounter Vehicle    163
47           Inflight Event / Encounter Bird / Animal    147
48           Ground Event / Encounter Gear Up Landing    141
49                  Ground Event / Encounter Aircraft    135
50                              Ground Incursion Ramp    128
51                  Inflight Event / Encounter Object    127
52                Ground Event / Encounter Fuel Issue    121
53      Deviation / Discrepancy - Procedural Security    109
54  Deviation / Discrepancy - Procedural Landing W...    108
55              Inflight Event / Encounter VFR In IMC    100
56    Ground Event / Encounter Person / Animal / Bird     96
57             No Specific Anomaly Occurred All Types     73
58                       Ground Event / Encounter FOD     63
59  Flight Deck / Cabin / Aircraft Event Passenger...     56
60                 Ground Event / Encounter Jet Blast     46
61          Inflight Event / Encounter Fly Away (UAS)     35
62                Inflight Event / Encounter Aircraft     34
63                              Ground Excursion Ramp     25
64                   Inflight Event / Encounter Laser     12
65        Ground Event / Encounter Loss Of VLOS (UAS)     12

### 3.3. Create Dummy Columns

In [11]:
# Obtain dummy columns
dummy_full = full.copy()
dummy_full['anomaly_code'] = dummy_full['anomaly_code'].str.replace(' ', '', regex=False)
dummies = dummy_full['anomaly_code'].str.get_dummies(sep=';')
# dummy_full = pd.concat([full.copy(), dummies], axis=1)

In [12]:
# Rename variables to include prefix "anomaly_"
rename = dummies.columns
rename_to = []
for x in rename:
    rename_to.append("anomaly_" + x)

dummies.columns=rename_to

In [13]:
# Concat with original data
dummy_full = pd.concat([full.acn, full.anomaly_code, dummies], axis=1)

In [14]:
with pd.option_context('display.max_rows', None):
    display(summarize_dataframe(dummy_full))

/tmp/ipykernel_1029/3979652495.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return pd.concat([missing_values, df.describe(include='all').transpose()], axis=1).fillna("")

,Data Type,Missing Values,Unique Values,count,unique,top,freq,mean,std,min,25%,50%,75%,max
acn,int64,0,33723,33723.0,,,,1828811.478783,192110.173434,1507557.0,1673862.5,1806271.0,1981117.5,2296796.0
anomaly_code,object,0,6659,33723.0,6659,Aircraft Equipment Problem Critical,1974,,,,,,,
anomaly_ATCIssueAllTypes,int64,0,2,33723.0,,,,0.178513,0.38295,0.0,0.0,0.0,0.0,1.0
anomaly_AircraftEquipmentProblemCritical,int64,0,2,33723.0,,,,0.243958,0.429474,0.0,0.0,0.0,0.0,1.0
anomaly_AircraftEquipmentProblemLessSevere,int64,0,2,33723.0,,,,0.166207,0.372272,0.0,0.0,0.0,0.0,1.0
anomaly_AirspaceViolationAllTypes,int64,0,2,33723.0,,,,0.037007,0.188783,0.0,0.0,0.0,0.0,1.0
anomaly_ConflictAirborneConflict,int64,0,2,33723.0,,,,0.045103,0.207533,0.0,0.0,0.0,0.0,1.0
anomaly_ConflictGroundConflict,int64,0,2,33723.0,,,,0.068025,0.251792,0.0,0.0,0.0,0.0,1.0
anomaly_ConflictNMAC,int64,0,2,33723.0,,,,0.098894,0.298524,0.0,0.0,0.0,0.0,1.0
anomaly_Critical,int64,0,2,33723.0,,,,0.053495,0.225021,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation-AltitudeCrossingRestrictionNotMet,int64,0,2,33723.0,,,,0.016458,0.127229,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation-AltitudeExcursionFromAssignedAltitude,int64,0,2,33723.0,,,,0.053999,0.226019,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation-AltitudeOvershoot,int64,0,2,33723.0,,,,0.033923,0.181035,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation-AltitudeUndershoot,int64,0,2,33723.0,,,,0.007591,0.086798,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation-SpeedAllTypes,int64,0,2,33723.0,,,,0.033034,0.178728,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation-Track/HeadingAllTypes,int64,0,2,33723.0,,,,0.070397,0.255819,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralClearance,int64,0,2,33723.0,,,,0.232571,0.422477,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralFAR,int64,0,2,33723.0,,,,0.116686,0.32105,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralHazardousMaterialViolation,int64,0,2,33723.0,,,,0.038609,0.192663,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralLandingWithoutClearance,int64,0,2,33723.0,,,,0.003203,0.056501,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralMEL/CDL,int64,0,2,33723.0,,,,0.018919,0.13624,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralMaintenance,int64,0,2,33723.0,,,,0.04451,0.206228,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralOther/Unknown,int64,0,2,33723.0,,,,0.005664,0.075046,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralPublishedMaterial/Policy,int64,0,2,33723.0,,,,0.567298,0.495458,0.0,0.0,1.0,1.0,1.0
anomaly_Deviation/Discrepancy-ProceduralSecurity,int64,0,2,33723.0,,,,0.003232,0.056761,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralUnauthorizedFlightOperations(UAS),int64,0,2,33723.0,,,,0.013967,0.117354,0.0,0.0,0.0,0.0,1.0
anomaly_Deviation/Discrepancy-ProceduralWeightAndBalance,int64,0,2,33723.0,,,,0.025205,0.156751,0.0,0.0,0.0,0.0,1.0
anomaly_FlightDeck/Cabin/AircraftEventIllness/Injury,int64,0,2,33723.0,,,,0.023574,0.151721,0.0,0.0,0.0,0.0,1.0
anomaly_FlightDeck/Cabin/AircraftEventOther/Unknown,int64,0,2,33723.0,,,,0.019067,0.136763,0.0,0.0,0.0,0.0,1.0
anomaly_FlightDeck/Cabin/AircraftEventPassengerElectronicDevice,int64,0,2,33723.0,,,,0.001661,0.040717,0.0,0.0,0.0,0.0,1.0
anomaly_FlightDeck/Cabin/AircraftEventPassengerMisconduct,int64,0,2,33723.0,,,,0.009163,0.095285,0.0,0.0,0.0,0.0,1.0
anomaly_FlightDeck/Cabin/AircraftEventSmoke/Fire/Fumes/Odor,int64,0,2,33723.0,,,,0.055867,0.229668,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterAircraft,int64,0,2,33723.0,,,,0.004003,0.063145,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterFOD,int64,0,2,33723.0,,,,0.001868,0.043182,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterFuelIssue,int64,0,2,33723.0,,,,0.003588,0.059794,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterGearUpLanding,int64,0,2,33723.0,,,,0.004181,0.064527,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterGroundEquipmentIssue,int64,0,2,33723.0,,,,0.018533,0.134872,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterGroundStrike-Aircraft,int64,0,2,33723.0,,,,0.01797,0.132844,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterJetBlast,int64,0,2,33723.0,,,,0.001364,0.036908,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterLossOfAircraftControl,int64,0,2,33723.0,,,,0.062361,0.241814,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterLossOfVLOS(UAS),int64,0,2,33723.0,,,,0.000356,0.018861,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterObject,int64,0,2,33723.0,,,,0.01281,0.112457,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterOther/Unknown,int64,0,2,33723.0,,,,0.032441,0.17717,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterPerson/Animal/Bird,int64,0,2,33723.0,,,,0.002847,0.053279,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterVehicle,int64,0,2,33723.0,,,,0.004833,0.069356,0.0,0.0,0.0,0.0,1.0
anomaly_GroundEvent/EncounterWeather/Turbulence,int64,0,2,33723.0,,,,0.012662,0.111812,0.0,0.0,0.0,0.0,1.0
anomaly_GroundExcursionRamp,int64,0,2,33723.0,,,,0.000741,0.027218,0.0,0.0,0.0,0.0,1.0
anomaly_GroundExcursionRunway,int64,0,2,33723.0,,,,0.029831,0.170124,0.0,0.0,0.0,0.0,1.0
anomaly_GroundExcursionTaxiway,int64,0,2,33723.0,,,,0.005901,0.076592,0.0,0.0,0.0,0.0,1.0
anomaly_GroundIncursionRamp,int64,0,2,33723.0,,,,0.003796,0.061493,0.0,0.0,0.0,0.0,1.0
anomaly_GroundIncursionRunway,int64,0,2,33723.0,,,,0.024968,0.15603,0.0,0.0,0.0,0.0,1.0
anomaly_GroundIncursionTaxiway,int64,0,2,33723.0,,,,0.016784,0.128462,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterAircraft,int64,0,2,33723.0,,,,0.001008,0.031737,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterBird/Animal,int64,0,2,33723.0,,,,0.004359,0.06588,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterCFTT/CFIT,int64,0,2,33723.0,,,,0.094298,0.292247,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterFlyAway(UAS),int64,0,2,33723.0,,,,0.001038,0.0322,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterFuelIssue,int64,0,2,33723.0,,,,0.027518,0.16359,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterLaser,int64,0,2,33723.0,,,,0.000356,0.018861,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterLossOfAircraftControl,int64,0,2,33723.0,,,,0.035021,0.183835,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterObject,int64,0,2,33723.0,,,,0.003766,0.061253,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterOther/Unknown,int64,0,2,33723.0,,,,0.011446,0.106374,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterUnstabilizedApproach,int64,0,2,33723.0,,,,0.036711,0.188054,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterVFRInIMC,int64,0,2,33723.0,,,,0.002965,0.054375,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterWakeVortexEncounter,int64,0,2,33723.0,,,,0.027044,0.162214,0.0,0.0,0.0,0.0,1.0
anomaly_InflightEvent/EncounterWeather/Turbulence,int64,0,2,33723.0,,,,0.085342,0.279395,0.0,0.0,0.0,0.0,1.0
anomaly_LessSevere,int64,0,2,33723.0,,,,0.014738,0.120503,0.0,0.0,0.0,0.0,1.0
anomaly_NoSpecificAnomalyOccurredAllTypes,int64,0,2,33723.0,,,,0.002165,0.046477,0.0,0.0,0.0,0.0,1.0
anomaly_NoSpecificAnomalyOccurredUnwantedSituation,int64,0,2,33723.0,,,,0.008926,0.094055,0.0,0.0,0.0,0.0,1.0

In [15]:
# Filter dummy_full to verify that the dummy codes worked as designed

dummy_ID = dummy_full[['acn', 'anomaly_code']]
dummy_cats = dummy_full.iloc[:, -72:]
dummy_cut = pd.concat([dummy_ID, dummy_cats], axis=1)

In [16]:
# View the filtered dataframe to verify

with pd.option_context('display.max_columns', None,
                        'display.max_colwidth', None,
                        'display.width', None):
    display(dummy_cut.head(25))

,acn,anomaly_code,acn,anomaly_code,anomaly_ATCIssueAllTypes,anomaly_AircraftEquipmentProblemCritical,anomaly_AircraftEquipmentProblemLessSevere,anomaly_AirspaceViolationAllTypes,anomaly_ConflictAirborneConflict,anomaly_ConflictGroundConflict,anomaly_ConflictNMAC,anomaly_Critical,anomaly_Deviation-AltitudeCrossingRestrictionNotMet,anomaly_Deviation-AltitudeExcursionFromAssignedAltitude,anomaly_Deviation-AltitudeOvershoot,anomaly_Deviation-AltitudeUndershoot,anomaly_Deviation-SpeedAllTypes,anomaly_Deviation-Track/HeadingAllTypes,anomaly_Deviation/Discrepancy-ProceduralClearance,anomaly_Deviation/Discrepancy-ProceduralFAR,anomaly_Deviation/Discrepancy-ProceduralHazardousMaterialViolation,anomaly_Deviation/Discrepancy-ProceduralLandingWithoutClearance,anomaly_Deviation/Discrepancy-ProceduralMEL/CDL,anomaly_Deviation/Discrepancy-ProceduralMaintenance,anomaly_Deviation/Discrepancy-ProceduralOther/Unknown,anomaly_Deviation/Discrepancy-ProceduralPublishedMaterial/Policy,anomaly_Deviation/Discrepancy-ProceduralSecurity,anomaly_Deviation/Discrepancy-ProceduralUnauthorizedFlightOperations(UAS),anomaly_Deviation/Discrepancy-ProceduralWeightAndBalance,anomaly_FlightDeck/Cabin/AircraftEventIllness/Injury,anomaly_FlightDeck/Cabin/AircraftEventOther/Unknown,anomaly_FlightDeck/Cabin/AircraftEventPassengerElectronicDevice,anomaly_FlightDeck/Cabin/AircraftEventPassengerMisconduct,anomaly_FlightDeck/Cabin/AircraftEventSmoke/Fire/Fumes/Odor,anomaly_GroundEvent/EncounterAircraft,anomaly_GroundEvent/EncounterFOD,anomaly_GroundEvent/EncounterFuelIssue,anomaly_GroundEvent/EncounterGearUpLanding,anomaly_GroundEvent/EncounterGroundEquipmentIssue,anomaly_GroundEvent/EncounterGroundStrike-Aircraft,anomaly_GroundEvent/EncounterJetBlast,anomaly_GroundEvent/EncounterLossOfAircraftControl,anomaly_GroundEvent/EncounterLossOfVLOS(UAS),anomaly_GroundEvent/EncounterObject,anomaly_GroundEvent/EncounterOther/Unknown,anomaly_GroundEvent/EncounterPerson/Animal/Bird,anomaly_GroundEvent/EncounterVehicle,anomaly_GroundEvent/EncounterWeather/Turbulence,anomaly_GroundExcursionRamp,anomaly_GroundExcursionRunway,anomaly_GroundExcursionTaxiway,anomaly_GroundIncursionRamp,anomaly_GroundIncursionRunway,anomaly_GroundIncursionTaxiway,anomaly_InflightEvent/EncounterAircraft,anomaly_InflightEvent/EncounterBird/Animal,anomaly_InflightEvent/EncounterCFTT/CFIT,anomaly_InflightEvent/EncounterFlyAway(UAS),anomaly_InflightEvent/EncounterFuelIssue,anomaly_InflightEvent/EncounterLaser,anomaly_InflightEvent/EncounterLossOfAircraftControl,anomaly_InflightEvent/EncounterObject,anomaly_InflightEvent/EncounterOther/Unknown,anomaly_InflightEvent/EncounterUnstabilizedApproach,anomaly_InflightEvent/EncounterVFRInIMC,anomaly_InflightEvent/EncounterWakeVortexEncounter,anomaly_InflightEvent/EncounterWeather/Turbulence,anomaly_LessSevere,anomaly_NoSpecificAnomalyOccurredAllTypes,anomaly_NoSpecificAnomalyOccurredUnwantedSituation
0,1507557,ATC Issue All Types; Deviation / Discrepancy - Procedural Published Material / Policy,1507557,ATC Issue All Types; Deviation / Discrepancy - Procedural Published Material / Policy,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1513720,Aircraft Equipment Problem Less Severe,1513720,Aircraft Equipment Problem Less Severe,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1513718,Flight Deck / Cabin / Aircraft Event Illness / Injury,1513718,Flight Deck / Cabin / Aircraft Event Illness / Injury,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1513706,Aircraft Equipment Problem Critical,1513706,Aircraft Equipment Problem Critical,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1513663,Aircraft Equipment Problem Less Severe; Deviation / Discrepancy - Procedural Weight And Balance,1513663,Aircraft Equipment Problem Less Severe; Deviation / Discrepancy - Procedural Weight And Balance,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,1513655,Deviation / Discrepancy - Procedural Published Material / Policy; Deviation / Discrepancy - Procedural Weight And Balance,1513655,Deviation / Discrepancy - Procedural Published Material / Policy; Deviation / Discrepancy - Procedural Weight And Balance,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1513614,Aircraft Equipment Problem Less Severe; Deviation - Altitude Overshoot,1513614,Aircraft Equipment Problem Less Severe; Deviation - Altitude Overshoot,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,1513606,ATC Issue All Types; Conflict Airborne Conflict; Deviation / Discrepancy - Procedural Published Material / Policy,1513606,ATC Issue All Types; Conflict Airborne Conflict; Deviation / Discrepancy - Procedural Published Material / Policy,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1513600,Deviation / Discrepancy - Procedural Published Material / Policy; Flight Deck / Cabin / Aircraft Event Illness / Injury; Flight Deck / Cabin / Aircraft Event Smoke / Fire / Fumes / Odor,1513600,Deviation / Discrepancy - Procedural Published Material / Policy; Flight Deck / Cabin / Aircraft Event Illness / Injury; Flight Deck / Cabin / Aircraft Event Smoke / Fire / Fumes / Odor,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1513569,Aircraft Equipment Problem Less Severe; Deviation / Discrepancy - Procedural FAR; Deviation / Discrepancy - Procedural Published Material / Policy; Ground Event / Encounter Loss Of Aircraft Control; Ground Excursion Runway; Ground Incursion Runway,1513569,Aircraft Equipment Problem Less Severe; Deviation / Discrepancy - Procedural FAR; Deviation / Discrepancy - Procedural Published Material / Policy; Ground Event / Encounter Loss Of Aircraft Control; Ground Excursion Runway; Ground Incursion Runway,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,1513565,Airspace Violation All Types; Deviation / Discrepancy - Procedural FAR; Deviation / Discrepancy - Procedural Published Material / Policy,1513565,Airspace Violation All Types; Deviation / Discrepancy - Procedural FAR; Deviation / Discrepancy - Procedural Published Material / Policy,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,1513755,Deviation / Discrepancy - Procedural Published Material / Policy,1513755,Deviation / Discrepancy - Procedural Published Material / Policy,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,1513561,Conflict NMAC; Deviation / Discrepancy - Procedural Published Material / Policy,1513561,Conflict NMAC; Deviation / Discrepancy - Procedural Published Material / Policy,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,1513436,Aircraft Equipment Problem Critical; Flight Deck / Cabin / Aircraft Event Smoke / Fire / Fumes / Odor,1513436,Aircraft Equipment Problem Critical; Flight Deck / Cabin / Aircraft Event Smoke / Fire / Fumes / Odor,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,1513434,ATC Issue All Types; Deviation - Altitude Overshoot; Deviation / Discrepancy - Procedural Clearance; Inflight Event / Encounter CFTT / CFIT,1513434,ATC Issue All Types; Deviation - Altitude Overshoot; Deviation / Discrepancy - Procedural Clearance; Inflight Event / Encounter CFTT / CFIT,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
15,1513430,Aircraft Equipment Problem Critical,1513430,Aircraft Equipment Problem Critical,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,1513429,Aircraft Equipment Problem Less Severe; Deviation - Altitude Excursion From Assigned Altitude,1513429,Aircraft Equipment Problem Less Severe; Deviation - Altitude Excursion From Assigned Altitude,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,1513381,ATC Issue All Types; Deviation - Speed All Types; Deviation / Discrepancy - Procedural FAR; Flight Deck / Cabin / Aircraft Event Illness / Injury,1513381,ATC Issue All Types; Deviation - Speed All Types; Deviation / Discrepancy - Procedural FAR; Flight Deck / Cabin / Aircraft Event Illness / Injury,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,1513375,Deviation / Discrepancy - Procedural Published Material / Policy,1513375,Deviation / Discrepancy - Procedural Published Material / Policy,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,1513344,ATC Issue All Types; Inflight Event / Encounter Other / Unknown,1513344,ATC Issue All Types; Inflight Event / Encounter Other / Unknown,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
20,1513320,Deviation - Track / Heading All Types; Deviation / Discrepancy - Procedural Clearance; Deviation / Discrepancy - Procedural Published Material / Policy; Deviation / Discrepancy - Procedural Landing Without Clearance; Ground Incursion Runway,1513320,Deviation - Track / Heading All Types; Deviation / Discrepancy - Procedural Clearance; Deviation / Discrepancy - Procedural Published Material / Policy; Deviation / Discrepancy - Procedural Landing Without Clearance; Ground Incursion Runway,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,1513314,Aircraft Equipment Problem Less Severe; Inflight Event / Encounter Weather / Turbulence; Inflight Event / Encounter Loss Of Aircraft Control,1513314,Aircraft Equipment Problem Less Severe; Inflight Event / Encounter Weather / Turbulence; Inflight Event / Encounter Loss Of Aircraft Control,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
22,1513310,Flight Deck / Cabin / Aircraft Event Other / Unknown; Ground Event / Encounter Ground Strike - Aircraft; Inflight Event / Encounter Unstabilized Approach; Inflight Event / Encounter Weather / Turbulence,1513310,Flight Deck / Cabin / Aircraft Event Other / Unknown; Ground Event / Encounter Ground Strike - Aircraft; Inflight Event / Encounter Unstabilized Approach; Inflight Event / Encounter Weather / Turbulence,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
23,1513498,Inflight Event / Encounter Unstabilized Approach; Inflight Event / Encounter Weather / Turbulence,1513498,Inflight Event / Encounter Unstabilized Approach; Inflight Event / Encounter Weather / Turbulence,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
24,1513304,ATC Issue All Types,1513304,ATC Issue All Types,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [17]:
# This looks finished, but we may opt to lump all the "other" categories into a single "other" cateogry

## 4. Export Data

In [18]:
# Export
#dummy_full.to_csv('Output/Data 1 - anomaly clean.csv', index=False)